### ISSUE TITLE
Missing dependency: jschardet

### ISSUE THREAD

**Issue by klren0312** [JohnstonCode/svn-scm#1542] opened 2021-11-23 02:09 UTC
- VSCode Version: 1.63.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.18363
- Extension Version: v2.15.0
- System Language: Chinese
- SVN Version: 1.14.0

## Issue ##
When I open the vscode,  it throw `Missing dependency: jschardet`

## Steps to Reproduce ##
Must present

## SVN Output ##
No output

## Screenshots ##
![1637633233(1)](https://user-images.githubusercontent.com/10903843/142961424-c3044554-5afc-420a-aa04-e3534ca33120.png)

**Comment by JohnstonCode** [comment] 2021-11-24 16:56
https://github.com/aadsm/jschardet/pull/73

**Comment by JohnstonCode** [comment] 2021-11-24 16:57
The issue is caused by this package no having a main set. I do this to reduce the bundle size as vs code is bundled with jschardet

**Comment by klren0312** [comment] 2021-11-25 01:29
Thanks, I temporary change to use `VSCode Version:  1.62.3`, it is available.

**Comment by adame11** [comment] 2021-12-09 00:17
Yes, I concur. You can get vscode version 1.62.3 here: https://code.visualstudio.com/updates/v1_62 ^

**Comment by ericcirone** [comment] 2021-12-09 01:42
So other than reverting to an older VSCode is there any fix for this?

**Comment by yufengkz** [comment] 2021-12-09 02:58
You can revert back to the old version。

**Comment by metal571** [comment] 2021-12-09 03:04
BTW 1.63.0 is now released as stable and so this is not just broken for Insiders anymore.

**Comment by ericcirone** [comment] 2021-12-09 04:07
> BTW 1.63.0 is now released as stable and so this is not just broken for Insiders anymore.

Right, that's why I was asking.

**Comment by makedopamine** [comment] 2021-12-09 05:39
oops! I should disable auto update.

**Comment by MaDill** [comment] 2021-12-09 09:38
Even with version 2.15.1 I still get this error.

In the log there are following errors:
[2021-12-09 10:32:25.387] [exthost] [error] Activating extension johnstoncode.svn-scm failed due to an error:
[2021-12-09 10:32:25.387] [exthost] [error] TypeError: Cannot read property 'Constants' of undefined
	at Object.1558 (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:171727)
	at r (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:362703)
	at Object.7494 (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:241894)
	at r (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:362703)
	at Object.2045 (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:134694)
	at r (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:362703)
	at Object.5049 (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:130007)
	at r (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:362703)
	at c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:362874
	at c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:365026
	at Object.<anonymous> (c:\Users\mdill\.vscode\extensions\johnstoncode.svn-scm-2.15.1\out\extension.js:2:365047)
	at Module.u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:32222)
	at Function.p._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:28887)
	at Function.f._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:61699)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.r [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
	at v._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:30297)
	at v._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:100:12958)
	at v._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:100:11931)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)

**Comment by slolo2000** [comment] 2021-12-09 09:54
I can confirm, I also have the same error with the version 2.15.1 of the plugin

VSCode Version: 1.63.0
OS Version: Windows 10 Pro 21H2 build 19044.1387
Extension Version: v2.15.1
System Language: English
SVN Version: 1.14.1.51187

**Comment by JohnstonCode** [comment] 2021-12-09 10:05
Yeah sorry about that i listed jschardet as a dev dep rather than a dep.

**Comment by slolo2000** [comment] 2021-12-09 10:12
Just one thing is strange with the new release.
Now the total of modified files does not appear on the icon (only the clock still remain)

![image](https://user-images.githubusercontent.com/10075509/145376841-7417feb5-d71a-4552-a657-6c1ffb8d0bea.png)

**Comment by MaDill** [comment] 2021-12-09 10:23
> Just one thing is strange with the new release. Now the total of modified files does not appear on the icon (only the clock still remain)

I can not see this. On my system it show the number like before.

Version: 1.63.0 (system setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Datum: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Betriebssystem: Windows_NT x64 10.0.19044

**Comment by klren0312** [comment] 2021-12-10 02:25
ok! it works in 
```
Version: 1.64.0-insider (user setup)
Commit: 68976705968229accd11fdfe1cba36a908208dc9
Date: 2021-12-09T05:19:16.534Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```
![1639103108(1)](https://user-images.githubusercontent.com/10903843/145506850-e2cadd15-1a51-4bd1-a881-f10bedd50623.png)

**Closed** 2021-12-10 02:36 UTC
Labels: upstream
