### ISSUE TITLE
Missing dependency: jschardet

### ISSUE THREAD

**Issue by karvaton** [JohnstonCode/svn-scm#1546] opened 2021-12-09 08:49 UTC
Issue Type: <b>Bug</b>

On opening svn

Extension version: 2.15.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.11.0-41-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.12GB (0.20GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id d0d0ef41-539e-41de-b3b1-82784a2a0f41|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by davnat** [comment] 2021-12-09 09:01
Same problem on Ubuntu 20.04, on upgrading to Code 1.63.
This is blocking for me, please provide a fix or at least a workaround.

**Comment by JohnstonCode** [comment] 2021-12-09 09:05
Duplicate of #1542

**Closed by JohnstonCode** 2021-12-09 09:05 UTC
