### ISSUE TITLE
Can i make Visual Studio Code highlight modified files in explorer view?

### ISSUE THREAD

**Issue by mionuxor** [JohnstonCode/svn-scm#1005] opened 2020-07-10 11:50 UTC
In source control tab they have "M" icon, but in explorer view no, they have (in my project only PHP icon). Changed files are not highlight  and tab is not highlight.
![1](https://user-images.githubusercontent.com/64301383/87151542-57227800-c2b4-11ea-825f-ef54c3a34672.PNG)
![2](https://user-images.githubusercontent.com/64301383/87151549-5b4e9580-c2b4-11ea-9304-a85ad4ab7c33.PNG)

**Comment by edgardmessias** [comment] 2020-07-10 11:54
The proposed api has been removed #675

Duplicate of #741

**Closed by edgardmessias** 2020-07-10 11:54 UTC
