### ISSUE TITLE
Official python extension with pylint runs on duplicate SVN files

### ISSUE THREAD

**Issue by Zeddicus414ce** [JohnstonCode/svn-scm#85] opened 2017-12-14 00:59 UTC
To start, I love the work you guys are doing! Excellent SVN package so far, thank you!

The problem: Pylint is wanting to lint svn files... So the warnings, etc are printed twice for every file. 
![image](https://user-images.githubusercontent.com/31261142/33970119-d830696a-e036-11e7-96c9-64aa2a451e5b.png)

I'm asking you guys for help since you might know what's up. It seems that the python extension settings should be capable of ignoring SVN files, but I have not been able to fix it on the Python extension side so far. I've tried a bunch of different ignore patterns there as well, such as this:
`    "python.linting.ignorePatterns": [
        ".vscode/*.py",
        "**/site-packages/**/*.py",
        "svn*/**"
    ]`

Another note is that if I click on the pylint warning messages for the SVN copy of the file, I can actually get two editors open of the same file and they are nearly identical. 

If you guys can help, it would be greatly appreciated.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
vscode-eslint|dba|1.4.3
xml|Dot|1.9.2
tslint|eg2|1.0.24
svn-scm|joh|1.4.5
mssql|ms-|1.3.0
python|ms-|0.8.0
vscode-code-outline|pat|0.0.12
vscode-icons|rob|7.19.0

**Comment by JohnstonCode** [comment] 2017-12-14 18:15
Thanks for raising this. I will look into it and sort something out.

**Comment by JohnstonCode** [comment] 2017-12-16 10:07
Seem the issue is with this line in the python extension

https://github.com/DonJayamanne/pythonVSCode/blob/c8db3459563964dfc6a06188e46a14f010221d69/src/client/providers/lintProvider.ts#L25

The Uri schemas to ignore are hard coded.

I will create a PR to have it added as a config option

**Comment by JohnstonCode** [comment] 2017-12-19 17:52
The changes have been merged in the python extension. Not sure when it will be rolled out tho.

**Closed by JohnstonCode** 2017-12-19 17:52 UTC

**Comment by Zeddicus414ce** [comment] 2017-12-19 18:41
@JohnstonCode , thanks so much for the timely and helpful work. I'm looking forward to using your extension without the pylint troubles!
