### ISSUE TITLE
the list of changed files is empty

### ISSUE THREAD

**Issue by tubylem** [JohnstonCode/svn-scm#683] opened 2019-10-11 08:41 UTC
Issue Type: <b>Bug</b>

after update, the SVN plugin stop working properly, list of changed files is empty after saving a file

Extension version: 1.54.6
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (25.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JohnstonCode** [comment] 2019-10-11 08:44
Duplicate of #681

**Closed by JohnstonCode** 2019-10-11 08:44 UTC
