### ISSUE TITLE
Missing dependency for SVN extension in vscode 1.63

### ISSUE THREAD

**Issue by IperStan** [JohnstonCode/svn-scm#1550] opened 2021-12-09 10:07 UTC
Issue Type: <b>Bug</b>

Hello, I've just updated vscode from 1.62.3 to 1.63 and the SVN extension is completely dead due to missing dependency.

The only way to get back to work is downgrading to vscode 1.62.3

Extension version: 2.15.2
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JohnstonCode** [comment] 2021-12-09 10:08
Duplicate of #1542

**Closed by JohnstonCode** 2021-12-09 10:08 UTC
