### ISSUE TITLE
svn 插件使用不了。

### ISSUE THREAD

**Issue by mumu-baba** [JohnstonCode/svn-scm#1545] opened 2021-12-09 06:24 UTC
Issue Type: <b>Bug</b>

Missing dependency: jschardet

Extension version: 2.15.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|--crash-reporter-id 8e6645b7-6dcd-4afb-90ae-11dc9fcc0979|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804:30404766
vs360:30404995
vsrem710cf:30405999

```

</details>

**Comment by hope250** [comment] 2021-12-09 06:46
back to 1.62

**Comment by JohnstonCode** [comment] 2021-12-09 09:04
Duplicate of #1542

**Closed by JohnstonCode** 2021-12-09 09:04 UTC
