### ISSUE TITLE
Broken SVN functionallity after update 1.63.0

### ISSUE THREAD

**Issue by ptrskg** [JohnstonCode/svn-scm#1547] opened 2021-12-09 09:09 UTC
After installation of VScode 1.63.0 i get the error message "Missing dependency: jschardet" on startup of and the installed SVN extension stopped working. See below for versions.
----------------------------------------------------
Name: SVN
Id: johnstoncode.svn-scm
Description: Integrated Subversion source control
Version: 2.15.0
Publisher: Chris Johnston
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm
-------------------------------------------------------------
Version: 1.63.0 (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by JohnstonCode** [comment] 2021-12-09 09:12
Duplicate of #1542

**Closed by JohnstonCode** 2021-12-09 09:12 UTC
