### ISSUE TITLE
Extension doesnt work with auth

### ISSUE THREAD

**Issue by emptyVoid** [JohnstonCode/svn-scm#89] opened 2017-12-20 09:44 UTC
- VSCode Version: 1.19.0
- OS Version: Ubuntu 16.04
- Extension Version: 1.4.6
- System Language: English (US)

Seeing this every time I launch VSCode:
```
Using svn 1.9.3 (r1718519) from svn
[.cmaketools.json]$ svn info --xml
[project]$ svn info --xml
[src]$ svn stat
[src]$ svn ls http://<redacted>/trunk --depth empty
[src]$ svn ls http://<redacted>/branches
[src]$ svn ls http://<redacted>/tags
svn: E170013: Unable to connect to a repository at URL 'http://<redacted>/tags'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

svn: E170013: Unable to connect to a repository at URL '<redacted>/branches'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

svn: E170013: Unable to connect to a repository at URL '<redacted>/trunk'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

[project]$ svn info --xml
```

Please note, the errors disappear after I manually execute `svn up` in the working copy.

**Comment by JohnstonCode** [comment] 2017-12-20 09:49
Does your Svn repo require a username and pass?

**Comment by emptyVoid** [comment] 2017-12-20 11:10
It does, though the credentials are in the Ubuntu's login keyring, the keyring is unlocked (blank password). And `svn up` does not ask for them when executed from terminal.

**Comment by JohnstonCode** [comment] 2017-12-20 11:14
I think because it still will be asking for it even if it is blank.

I will need to add auth a setting to the extension to get this to work for you without having to do the "svn up" first.

**Comment by edgardmessias** [comment] 2018-01-31 19:44
@JohnstonCode, my idea:
* For `http://` and `svn://`, use the arguments `--username` and `--password`
* For `svn+ssh://`, use `sshpass -p`

Flow:
For commands without a remote query, do not use authentication, like, `add`, `info`, `status` (Note: check revion `HEAD`)

For commands with a remote query:
* First check remote access: like `svn info -r HEAD`
* If success, mark repository.ts authenticated, and run the other commands normally
* If fail, prompt to user and store in repository.ts and run the other commands normally

**Comment by JohnstonCode** [comment] 2018-02-01 09:23
Yeah that seems like a nice and simple approach

**Comment by JohnstonCode** [comment] 2018-02-12 17:06
Working on this now

**Comment by johnjacobkenny** [comment] 2018-02-12 17:22
Not sure if this is useful, but on my work computer running windows, it doesn't have this issue. Does svn automatically use windows credentials to connect?

**Comment by JohnstonCode** [comment] 2018-02-12 17:57
Anyone have access to a password protected SVN server. Cant test auth on local repos.

**Comment by edgardmessias** [comment] 2018-02-12 18:00
For local teste: http://svnbook.red-bean.com/en/1.7/svn.serverconfig.svnserve.html#svn.serverconfig.svnserve.auth

**Comment by JohnstonCode** [comment] 2018-02-12 18:08
Yeah tried that but doesnt want to ask me for the username or password

**Comment by edgardmessias** [comment] 2018-02-12 18:10
You can test with `--no-auth-cache` argument

**Comment by edgardmessias** [comment] 2018-02-12 18:11
Try remove files:
* Windows: `%APPDATA%\Subversion\auth\svn.simple\`
* Linux: `~/.subversion/auth/svn.simple/`

**Comment by JohnstonCode** [comment] 2018-02-12 18:23
still no joy

**Comment by edgardmessias** [comment] 2018-02-12 18:23
In folder of server, edit `conf/svnserve.conf`
Change:
```
[general]
anon-access = none
password-db = passwd
```

**Comment by JohnstonCode** [comment] 2018-02-12 18:25
yeah got

`anon-access = none
auth-access = write
password-db = passwd
authz-db = authz`

**Comment by JohnstonCode** [comment] 2018-02-12 18:32
im checking out using file:/// does that matter?

**Comment by edgardmessias** [comment] 2018-02-12 18:34
Yes, you need first, run: `svnserve -d --foreground -r <svn server folder>`

To checkout: `svn://localhost/`

**Comment by JohnstonCode** [comment] 2018-02-12 18:37
Works thanks for that

**Comment by JohnstonCode** [comment] 2018-02-12 19:39
@edgardmessias 

Thoughts on this commit? [Here](https://github.com/JohnstonCode/svn-scm/commit/41a8a24b89565ad1c414e301b77cbdf3a55c9cd4)

**Comment by edgardmessias** [comment] 2018-02-12 19:48
My idea: Override the `retryRun` to catch `need auth`, after this, prompt username and password.

Some commands not need auth, like `cat`, `diff`.

**Comment by edgardmessias** [comment] 2018-02-12 19:57
I not like the `window.showInput....` int the repository.ts, create a command (like `svn.promptAuth`) and call from repository.ts

In command.ts, you force to define the need auth to true.

**Comment by JohnstonCode** [comment] 2018-02-12 20:11
Yeah feels  wrong were it currently is.

I think the limit is need aswell otherwise it will just loop forever.

I was also thinknig should we add a config option for `--no-auth-cache` as svn stores everything in plaintext. If so the user will be asked for the password everytime the extension runs. or it will just use the cache.

**Comment by edgardmessias** [comment] 2018-02-12 20:14
I will make my version to you understand. Wait for tomorrow

**Comment by JohnstonCode** [comment] 2018-02-12 20:14
okay

**Comment by JohnstonCode** [comment] 2018-02-12 22:58
The more I think about it the more I think that the auth check should be in the model. There is no point in doing all the repository creation work if it can’t be accessed. The model is already responsible for finding the route path of a repository so why not check auth as well.

**Comment by edgardmessias** [comment] 2018-02-12 23:00
Think about how it would work in offline mode.

**Comment by JohnstonCode** [comment] 2018-02-12 23:08
My idea was only to flag that auth is needed in the model and pass it to the repository as the root path is.

**Comment by edgardmessias** [comment] 2018-02-13 16:35
@JohnstonCode, see #164

**Comment by emptyVoid** [comment] 2018-02-22 05:02
Does this fix apply to version 1.20.0?
I saw `@edgardmessias Added auth support` in the changelog and thought to try it out. Haven't noticed any change in behavior.

**Comment by JohnstonCode** [comment] 2018-02-22 08:43
Yes, it does.

Are you still unable to use the extension with auth?

**Comment by emptyVoid** [comment] 2018-02-22 10:24
Yes, I keep getting similar output on VSCode launch:
```
Using svn 1.9.3 (r1718519) from svn
[src]$ svn info --xml
[src]$ svn stat --xml --no-ignore
[src]$ svn info --xml
[src]$ svn log -r BASE:HEAD -q --xml
svn: E170013: Unable to connect to a repository at URL 'http://<redacted>/trunk/src'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
```
And an `Error Unable to update` when trying to manually update via the source control tab, with the following output:
```
[src]$ svn update
svn: E170013: Unable to connect to a repository at URL 'http://<redacted>/trunk'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
```
Same as before the extension starts working after an `svn up` from the terminal.

**Comment by emptyVoid** [comment] 2018-02-22 11:34
Yes, the replacement changed extension's behavior.
Now on every VSCode launch I'm prompted to enter username/password for the repository. Not sure if it's actually the intended behavior though, it's kind of an inconvenience, as `svn` from terminal doesn't ask for them.

**Comment by edgardmessias** [comment] 2018-02-22 11:42
Yes, is intended behavior.

The problem is GNOME Keyring.

Open `~/.subversion/config` and paste this section: `[auth]` > `password-stores`

Try set `password-stores=` (empty) and run three times the vscode

**Comment by emptyVoid** [comment] 2018-02-23 04:50
Thanks!
Twiddling with `password-stores` helped. Now I'm no longer prompted for user/pass.

Another concern: I'd noticed diffs did't work when the extension was unable to authenticate with repository; shouldn't it be able to show local changes without a connection?

**Comment by JohnstonCode** [comment] 2018-02-23 09:31
If you are left clicking on something in the SCM view then it would depend on the `svn.diff.withHead` setting.

**Comment by edgardmessias** [comment] 2018-02-27 16:25
Closed in favor of #188

**Closed by edgardmessias** 2018-02-27 16:25 UTC
Labels: bug

**Comment by faizanakram99** [comment] 2018-04-19 07:01
I am still being prompted with username and password every time I open vscode, it is annoying. I am using Ubuntu 18.04

**Comment by edgardmessias** [comment] 2018-04-19 14:40
@faizanakram99, open `~/.subversion/config` and paste the `password-stores` config

**Comment by faizanakram99** [comment] 2018-04-26 05:59
@edgardmessias Sorry for late reply, I didn't get a notification

password-stores
```

# password-stores = gpg-agent,gnome-keyring,kwallet
### To disable all password stores, use an empty list:
password-stores =
```
