### ISSUE TITLE
SVN update fails when authentication is needed

### ISSUE THREAD

**Issue by sushruth** [JohnstonCode/svn-scm#93] opened 2017-12-22 19:37 UTC
- VSCode Version: 1.19.1
- OS Version: OSX Sierra
- Extension Version: 1.5.0
- System Language: English ?
----
#### Issue

SVN Update fails when authentication is required. However, it runs fine in terminal.

----

Steps to Reproduce:

1. Click on "SVN update" from source control

```
Using svn 1.9.4 (r1740329) from /usr/bin/svn
[BRANCH_NAME]$ svn info --xml
[BRANCH_NAME]$ svn stat
[BRANCH_NAME]$ svn ls https://---REMOVED---/trunk --depth empty
[BRANCH_NAME]$ svn ls https://---REMOVED---/branches
[BRANCH_NAME]$ svn ls https://---REMOVED---/tags
svn: E170013: Unable to connect to a repository at URL 'https://---REMOVED---/branches'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

svn: E170013: Unable to connect to a repository at URL 'https://---REMOVED---/tags'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

svn: E170013: Unable to connect to a repository at URL 'https://---REMOVED---/trunk'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

[BRANCH_NAME]$ svn info --xml
[BRANCH_NAME]$ svn update
svn: E170013: Unable to connect to a repository at URL 'https://---REMOVED---/branches/BRANCH_NAME'
svn: E215004: No more credentials or we tried too many times.
Authentication failed

[BRANCH_NAME]$ svn stat
[BRANCH_NAME]$ svn info --xml

```

**Comment by JohnstonCode** [comment] 2017-12-22 20:52
Hi @sushruth 

Thanks for raising this. This is a dupe of #89 and somethnig i am working on

**Closed by JohnstonCode** 2017-12-22 20:52 UTC
